services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: zenee_web:latest
    container_name: zenee_web_container
    ports:
      - "3000:3000"
    restart: always
    # environment:
    #  - NODE_ENV=production
    volumes:
      - ./logs:/app/logs